import { ArrowUpRight, BarChart3, CircleDollarSign, Gauge, Network, Plus, ShieldCheck, Sparkles } from 'lucide-react'
import { PageHeader } from '../../ui/PageHeader'
import { copy, type TextFn } from '../../ui/copy'
import type { ModuleKey } from '../../app/navigation'

const projectCards = [
  { title: 'OrderFlow Platform', type: 'Production architecture', health: 92, status: 'Review ready', tone: 'teal', meta: 'AWS / EKS · 2,000 orders/sec · RPO 5m' },
  { title: 'Xshield On-Prem', type: 'Security platform', health: 78, status: 'Needs decision', tone: 'amber', meta: 'DC / DR · 1,500 agents · HA quorum' },
  { title: 'Data Lake Modernization', type: 'Investment case', health: 64, status: 'Draft', tone: 'coral', meta: 'S3 + Glue + Iceberg · 5-year horizon' },
]

export function Overview({ text, onOpenInvestment, onNavigate }: { text: TextFn; onOpenInvestment: () => void; onNavigate: (key: ModuleKey) => void }) {
  return <div className="page-content">
    <PageHeader eyebrow={text(copy('PERSONAL ARCHITECT WORKSPACE', 'PERSONAL ARCHITECT WORKSPACE'))} title={text(copy('Từ quyết định đến giá trị.', 'From decisions to value.'))} description={text(copy('Một workspace để thiết kế, kiểm chứng và tối ưu hệ thống cloud, on-premises và hybrid.', 'One workspace to design, validate, and optimize cloud, on-premises, and hybrid systems.'))} text={text} action={<button className="primary-button" onClick={onOpenInvestment}><Plus size={17} /> {text(copy('Tạo investment case', 'New investment case'))}</button>} />
    <div className="hero-strip"><div className="hero-copy"><div className="hero-kicker"><Sparkles size={15} /> DECISION INTELLIGENCE</div><h2>One clear view of your architecture.</h2><p>Connect assumptions, deployment evidence, performance signals and financial value before you commit.</p><div className="hero-links"><button onClick={() => onNavigate('architecture')}>Open architecture canvas <ArrowUpRight size={15} /></button><button onClick={() => onNavigate('investment')}>Review value signals <ArrowUpRight size={15} /></button></div></div><div className="hero-map"><div className="map-line line-one" /><div className="map-line line-two" /><div className="map-node node-a">REQ</div><div className="map-node node-b">ADR</div><div className="map-node node-c">TARGET</div><div className="map-node node-d">ROI</div><div className="map-label label-a">requirements</div><div className="map-label label-b">architecture</div><div className="map-label label-c">deployment target</div></div></div>
    <section className="section-block"><div className="section-heading"><div><div className="eyebrow">ACTIVE PORTFOLIO</div><h2>Projects in motion</h2></div><button className="text-button" onClick={() => onNavigate('architecture')}>View all <ArrowUpRight size={15} /></button></div><div className="project-grid">{projectCards.map((project) => <ProjectCard key={project.title} project={project} />)}</div></section>
    <div className="overview-grid"><section className="panel"><div className="section-heading compact"><div><div className="eyebrow">DECISION QUEUE</div><h2>Needs your attention</h2></div><span className="count-badge">03</span></div><div className="attention-list"><Attention icon={<ShieldCheck size={17} />} title="Validate DR quorum assumption" meta="Xshield On-Prem · architecture review" tone="red" /><Attention icon={<CircleDollarSign size={17} />} title="Compare 5-year storage TCO" meta="Data Lake Modernization · finance input" tone="amber" /><Attention icon={<Gauge size={17} />} title="Attach load test evidence" meta="OrderFlow Platform · release gate" tone="blue" /></div></section><section className="panel value-panel"><div className="section-heading compact"><div><div className="eyebrow">VALUE SNAPSHOT</div><h2>Architecture health</h2></div><BarChart3 size={18} className="muted-icon" /></div><div className="health-score"><div className="score-ring"><strong>82</strong><span>/ 100</span></div><div><strong>Good foundation</strong><p>3 decisions need evidence<br />before the next review cycle.</p></div></div><div className="metric-row"><span>Traceability coverage</span><strong>76%</strong><div className="meter"><i style={{ width: '76%' }} /></div></div><div className="metric-row"><span>Evidence freshness</span><strong>68%</strong><div className="meter"><i className="amber-meter" style={{ width: '68%' }} /></div></div></section></div>
  </div>
}

function ProjectCard({ project }: { project: typeof projectCards[number] }) { return <article className="project-card"><div className={`project-icon ${project.tone}`}><Network size={18} /></div><div className="project-card-top"><span className="mini-label">{project.type}</span><span className={`status-pill ${project.tone}`}>{project.status}</span></div><h3>{project.title}</h3><p>{project.meta}</p><div className="project-footer"><div className="mini-meter"><i style={{ width: `${project.health}%` }} /></div><strong>{project.health}%</strong><ArrowUpRight size={15} /></div></article> }
function Attention({ icon, title, meta, tone }: { icon: React.ReactNode; title: string; meta: string; tone: string }) { return <button className="attention-item"><span className={`attention-icon ${tone}`}>{icon}</span><span className="attention-copy"><strong>{title}</strong><small>{meta}</small></span><ArrowUpRight size={15} /></button> }
