import { useState } from 'react'
import { CheckCircle2, FileCheck2 } from 'lucide-react'
import { PageHeader } from '../../ui/PageHeader'
import { copy, type TextFn } from '../../ui/copy'
import { canMarkReviewed, defaultReviewChecklist, type ReviewItem, type ReviewState } from '../../domain/review'

export function Decisions({ text }: { text: TextFn }) {
  const [items, setItems] = useState<ReviewItem[]>(() => defaultReviewChecklist)
  const [status, setStatus] = useState<'draft' | 'under_review' | 'reviewed'>('draft')
  const [message, setMessage] = useState('')
  function updateItem(id: string, state: ReviewState) { setItems(items.map((item) => item.id === id ? { ...item, state } : item)) }
  function requestReview() { setStatus('under_review'); setMessage(text(copy('ADR đã chuyển sang under review.', 'ADR moved to under review.'))) }
  function markReviewed() { if (!canMarkReviewed(items)) { setMessage(text(copy('Chưa thể đánh dấu reviewed: còn checklist bắt buộc chưa pass.', 'Cannot mark reviewed: mandatory checklist items are not complete.'))); return } setStatus('reviewed'); setMessage(text(copy('Decision đã được self-reviewed cho revision hiện tại.', 'Decision self-reviewed for the current revision.'))) }
  return <div className="page-content"><PageHeader eyebrow="ADR & SELF-REVIEW" title={text(copy('Quyết định có thể kiểm tra lại.', 'Decisions that can be revisited.'))} description={text(copy('Lưu trade-off, bằng chứng và checklist tự review trước khi đóng một architecture revision.', 'Capture trade-offs, evidence, and a self-review checklist before closing an architecture revision.'))} text={text} action={<button className="primary-button" onClick={requestReview}><FileCheck2 size={17} /> {text(copy('Bắt đầu self-review', 'Start self-review'))}</button>} /><div className="decision-layout"><section className="panel adr-card"><div className="decision-status"><span className={`status-pill ${status === 'reviewed' ? 'teal' : status === 'under_review' ? 'amber' : 'coral'}`}>{status.replace('_', ' ')}</span><span className="mini-label">ADR-024 · revision 3</span></div><h2>Choose the event backbone</h2><p className="muted-copy">Select a messaging approach for OrderFlow. The decision balances reliability, operational effort, cost, and portability.</p><div className="adr-option selected-option"><div><strong>Amazon MSK</strong><span>Managed Kafka · high throughput · 7.4 / 10 weighted score</span></div><CheckCircle2 size={18} /></div><div className="adr-option"><div><strong>SQS + SNS</strong><span>Lower operations · simpler semantics · 7.1 / 10</span></div><span className="option-score">rejected</span></div><div className="adr-meta"><span>Owner <strong>Architect</strong></span><span>Evidence <strong>8 items</strong></span><span>UCROPS <strong>3.3 / 5</strong></span></div><button className="secondary-button full-button" onClick={markReviewed}><CheckCircle2 size={16} /> {text(copy('Đánh dấu reviewed', 'Mark as reviewed'))}</button>{message && <div className="form-message">{message}</div>}</section><section className="panel review-card"><div className="section-heading compact"><div><div className="eyebrow">SELF-REVIEW CHECKLIST</div><h2>Quality gates</h2></div><span className="status-pill amber">{items.filter((item) => item.state === 'pass').length}/{items.length} pass</span></div>{items.map((item) => <div className="review-row" key={item.id}><div className={`review-check ${item.state}`}>{item.state === 'pass' ? 'OK' : item.state === 'not_applicable' ? 'N/A' : '!'}</div><div><strong>{item.label}</strong><small>{item.mandatory ? 'required' : 'optional'}</small></div><select value={item.state} onChange={(event) => updateItem(item.id, event.target.value as ReviewState)}><option value="open">Open</option><option value="pass">Pass</option><option value="fail">Fail</option><option value="not_applicable">N/A</option></select></div>)}</section></div></div>
}
