import { useMemo, useState } from 'react'
import { FileCheck2, ShieldCheck, Upload, X } from 'lucide-react'
import { copy, type TextFn } from '../../ui/copy'

export function InvestmentModal({ text, onClose }: { text: TextFn; onClose: () => void }) {
  const [purchase, setPurchase] = useState(148000)
  const [annualRun, setAnnualRun] = useState(93000)
  const [years, setYears] = useState(5)
  const [benefit, setBenefit] = useState(42000)
  const results = useMemo(() => { const investment = purchase + annualRun; const totalBenefit = benefit * years; const roi = ((totalBenefit - investment) / investment) * 100; const payback = benefit > 0 ? purchase / benefit : 0; return { investment, totalBenefit, roi, payback } }, [purchase, annualRun, years, benefit])
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="modal"><div className="modal-header"><div><div className="eyebrow">NEW INVESTMENT CASE</div><h2>Model a technology decision</h2><p>Use your baseline data and make every assumption visible.</p></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div><div className="modal-body"><div className="form-column"><label>Case name<input defaultValue="Modernize data platform" /></label><label>Baseline / candidate<select defaultValue="AWS Aurora vs self-managed"><option>AWS Aurora vs self-managed</option><option>EKS vs EC2 estate</option><option>Storage refresh</option></select></label><div className="form-grid"><label>One-time investment<input type="number" value={purchase} onChange={(event) => setPurchase(Number(event.target.value))} /></label><label>Annual run cost<input type="number" value={annualRun} onChange={(event) => setAnnualRun(Number(event.target.value))} /></label></div><div className="range-field"><div><label>Analysis horizon</label><strong>{years} years</strong></div><input type="range" min="3" max="7" value={years} onChange={(event) => setYears(Number(event.target.value))} /></div><div className="range-field"><div><label>Annual measurable benefit</label><strong>${benefit.toLocaleString()}</strong></div><input type="range" min="10000" max="100000" step="1000" value={benefit} onChange={(event) => setBenefit(Number(event.target.value))} /></div><div className="import-box"><Upload size={18} /><div><strong>{text(copy('Nhập dữ liệu mua sắm', 'Import purchase data'))}</strong><span>Excel or CSV · historical price baseline</span></div><button className="text-button">Choose file</button></div></div><div className="calculation-column"><div className="eyebrow">EXPECTED SCENARIO</div><div className="result-card primary-result"><span>Projected ROI</span><strong>{results.roi.toFixed(1)}%</strong><small>{results.roi >= 0 ? 'positive value signal' : 'needs a better case'}</small></div><div className="result-card"><span>Total modeled value</span><strong>${Math.round(results.totalBenefit).toLocaleString()}</strong><small>{years}-year benefit</small></div><div className="result-card"><span>Payback period</span><strong>{results.payback.toFixed(1)} <small>years</small></strong><small>based on annual benefit</small></div><div className="calculation-note"><ShieldCheck size={16} /><span>All outputs retain formula, assumptions and source confidence for review.</span></div></div></div><div className="modal-footer"><button className="secondary-button" onClick={onClose}>{text(copy('Hủy', 'Cancel'))}</button><button className="primary-button" onClick={onClose}><FileCheck2 size={16} /> {text(copy('Lưu draft case', 'Save draft case'))}</button></div></div></div>
}
