import { Boxes, Cloud, Gauge, Plus, Upload } from 'lucide-react'
import { PageHeader } from '../../ui/PageHeader'
import { DatabaseIcon } from '../../ui/DatabaseIcon'
import { copy, type TextFn } from '../../ui/copy'

// KNOWN LIMITATION, carried forward unchanged by task 1.1 (pure refactor):
// every number below is hard-coded HTML. `src/domain/sizing.ts` v2.0 is the
// corrected engine and this screen does not import it yet. Wiring it up is
// task 3.4 in `docs/development/systemsarchitect-build-scope.md`, deliberately
// out of scope here so the before/after DOM stays byte-identical.
export function Sizing({ text }: { text: TextFn }) { return <div className="page-content"><PageHeader eyebrow="SIZING STUDIO" title={text(copy('Ước lượng trước khi xây.', 'Estimate before you build.'))} description={text(copy('Mô hình hóa API, database, Kubernetes, storage, network và firewall theo workload.', 'Model API, database, Kubernetes, storage, network, and firewall against workload.'))} text={text} action={<button className="primary-button"><Plus size={17} /> {text(copy('Tạo scenario', 'New scenario'))}</button>} /><div className="sizing-summary"><div className="metric-card"><span>Peak traffic</span><strong>2,000 <small>RPS</small></strong><em>+18% headroom</em></div><div className="metric-card"><span>Data growth</span><strong>4.8 <small>TB / year</small></strong><em>retention: 18 months</em></div><div className="metric-card"><span>Compute envelope</span><strong>18 <small>nodes</small></strong><em>3 AZ · EKS</em></div><div className="metric-card"><span>Monthly estimate</span><strong>$8.6k</strong><em className="positive">within budget</em></div></div><div className="panel sizing-table"><div className="section-heading compact"><div><div className="eyebrow">CAPACITY MODEL</div><h2>OrderFlow / expected scenario</h2></div><button className="secondary-button"><Upload size={15} /> Export inputs</button></div><table><thead><tr><th>Domain</th><th>Input</th><th>Calculated</th><th>Confidence</th><th>State</th></tr></thead><tbody><tr><td><strong><Gauge size={15} /> API</strong></td><td>2,000 RPS · 65% peak factor</td><td>12 × t3.medium</td><td><span className="confidence high">High</span></td><td><span className="status-pill teal">Ready</span></td></tr><tr><td><strong><Boxes size={15} /> Kubernetes</strong></td><td>3 AZ · 30 services</td><td>6 worker nodes</td><td><span className="confidence medium">Medium</span></td><td><span className="status-pill amber">Validate</span></td></tr><tr><td><strong><Cloud size={15} /> Storage</strong></td><td>4.8 TB/year · RF 3</td><td>18 TB usable</td><td><span className="confidence high">High</span></td><td><span className="status-pill teal">Ready</span></td></tr><tr><td><strong><DatabaseIcon /> Database</strong></td><td>2k writes/sec · 18 mo</td><td>Aurora r6g.large</td><td><span className="confidence low">Low</span></td><td><span className="status-pill coral">Needs test</span></td></tr></tbody></table></div></div> }
